### ISSUE TITLE
NavigationLink does not working while searching

### ISSUE THREAD

**Issue by FUNKYJASPER2** [markvanwijnen/NavigationSearchBar#2]
when implanting a navigation link on the search results the pressed cell will stay highlighted and do nothing.

**Comment by markvanwijnen** [comment]
This is a quick reply.

I am aware of this is "issue" I also found out why. The Results View Controller is a View Controller on his own , it is not aware of the outer NavigationView. When you place a NavigationLink it will search for a NavigationController which is not there hence the behavior you are seeing.

There is a work around, although not ideal. The Search Results can access State.

Within the NavigationView place some code like this:
`
@State private var navigationLinkIndex: Int = 0 
...
NavigationView {
            NavigationLink(destination: Text("Some Destination")), isActive: $navigationLinkIndex == 1) {
                EmptyView()
            }
}
`

Then in the Search Results replace NavigationLink for Button and when tapped change the state of navigationLinkIndex.

Also haven't tried this code, this is just a thought.

**Comment by markvanwijnen** [comment]
I am aware of this issue, I am looking into it now.

**Comment by FUNKYJASPER2** [comment]
sweet sounds good, let me know if you make any progress

**Comment by markvanwijnen** [comment]
The problem is that UISearchController is not pushed on to the main UINavigationController that you define with NavigationView. The Search Results are shown as a View on top of the current view. When NavigationLink looks at UISearchController it finds no UINavigationController and that's why you see the disabled state.

Now I thought perhaps by wrapping it in its own UINavigationController I could maybe get away with forwarding the events to the main UINavigationController. It did work, but the NavigationLink will not be deselected and you can't tap it again.

If you want a work around, this is a good way to do it:
```swift
struct ContentView: View {
    @State var text: String = ""
    @State var scopeSelection: Int = 0
    
    @State var navigationSelection: Int? = nil

    var body: some View {
        NavigationView {
            List {
                ForEach(1..<5) { index in
                    Text("Sample Text")
                }
            }
            .overlay(
                Group {
                    NavigationLink(destination: Text("Destination A"), tag: 1, selection: $navigationSelection) { EmptyView() }
                    NavigationLink(destination: Text("Destination B"), tag: 2, selection: $navigationSelection) { EmptyView() }
                }
            )
            .navigationTitle("Navigation")
            .navigationSearchBar(text: $text,
                                 scopeSelection: $scopeSelection,
                                 options: [
                                    .automaticallyShowsSearchBar: true,
                                    .obscuresBackgroundDuringPresentation: true,
                                    .hidesNavigationBarDuringPresentation: true,
                                    .hidesSearchBarWhenScrolling: false,
                                    .placeholder: "Search",
                                    .showsBookmarkButton: true,
                                    .scopeButtonTitles: ["All", "Missed", "Other"]
                                 ],
                                 actions: [
                                    .onCancelButtonClicked: {
                                        print("Cancel")
                                    },
                                    .onSearchButtonClicked: {
                                        print("Search")
                                    },
                                    .onBookmarkButtonClicked: {
                                        print("Present Bookmarks")
                                    }
                                 ], searchResultsContent: {
                                    List {
                                        Text("Search Results for \(text) in \(String(scopeSelection))")
                                        HStack {
                                            Button("Destination A") { self.navigationSelection = 1 }
                                            Spacer()
                                            Image(systemName: "chevron.right").foregroundColor(.secondary)
                                        }
                                        HStack {
                                            Button("Destination B") { self.navigationSelection = 2 }
                                            Spacer()
                                            Image(systemName: "chevron.right").foregroundColor(.secondary)
                                        }
                                    }
                                    .navigationTitle("New Nav")
                                 })
        }
    }
}
```

**Comment by lorenzofiamingo** [comment]
Same problem here... I'm not using this framework but my code is very similar to yours.
I "solved" by overriding some `Wrapper`  methods:
```swift
override func viewWillAppear(_ animated: Bool) {
    parent!.addChild(searchController.searchResultsController!)
    searchController.view.layoutIfNeeded().
    ...
}
override func viewDidAppear(_ animated: Bool) {
    parent!.addChild(searchController.searchResultsController!)
    searchController.view.layoutIfNeeded()
    ...
}
```
Of course now the frame of searchResultsController has changed... maybe could exist a way to restore it.
Hope this could help finding a solution.

This is my complete `Wrapper`:
```swift
class Controller: UIViewController {

    let hidesSearchBarWhenScrolling: Bool

    let searchController: UISearchController
    
    init(hidesSearchBarWhenScrolling: Bool, searchController: UISearchController) {
        self.hidesSearchBarWhenScrolling = hidesSearchBarWhenScrolling
        self.searchController = searchController
        super.init(nibName: nil, bundle: nil)
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override func willMove(toParent parent: UIViewController?) {
        self.parent?.navigationItem.searchController = searchController
        self.parent?.navigationItem.hidesSearchBarWhenScrolling = hidesSearchBarWhenScrolling
        self.parent?.navigationController?.navigationBar.sizeToFit()
    }

    override func viewWillAppear(_ animated: Bool) {
        parent!.addChild(searchController.searchResultsController!)
        searchController.view.layoutIfNeeded()
    }
    override func viewDidAppear(_ animated: Bool) {
        parent!.addChild(searchController.searchResultsController!)
        searchController.view.layoutIfNeeded()
        
    }
}
```

**Comment by markvanwijnen** [comment]
Thanks @lorenzofiamingo that worked!

**Comment by lorenzofiamingo** [comment]
@markvanwijnen Great! How did you manage to restore the frame of searchResultsController?

**Comment by markvanwijnen** [comment]
What do you mean by restoring the frame? I added your code and the NavigationLink worked, it took me to another screen with Destination and a back button appeared so I can move back. Maybe I am missing something?

The new version is online so you can have a look if you want.

**Comment by lorenzofiamingo** [comment]
In my code the frame of searchResultsController didn't take into account the top navigation bar, so the bar was covering part of the frame. If this is not happening anymore is great. I'll take a look!

**Comment by markvanwijnen** [comment]
Would love to hear if the same happens with my code. If so, could you please show the code so I can look at it too?

**Comment by bobmatteo** [comment]
Hi @markvanwijnen I have the same issue as @lorenzofiamingo. I am using a list in the searchResultsContent which is working fine only the first few items in the list are displayed behind the (active) search bar area.

**Comment by markvanwijnen** [comment]
Hi bob, thanks for showing the GIF to clarify the issue. 
I was able to fix it, I will post the solution soon.

**Comment by markvanwijnen** [comment]
Could you update the package to 1.2.1 and confirm that the issue has been resolved?

**Comment by bobmatteo** [comment]
> Could you update the package to 1.2.1 and confirm that the issue has been resolved?

Yes it's perfect now! Awesome, and super fast fix! Thanks

**Comment by FUNKYJASPER2** [comment]
I'm slightly confused right now. So is the code that is being posted here solve the issue with the navigation link staying highlighted? And if so how would I implement that? 

As right now whenever I click on the navigationlink and then go back, the cell in the list will continue to stay highlighted.

**Comment by markvanwijnen** [comment]
Hi Jasper,

You are right. It is confusing since the two issues weren't related. It should have been separated in different issues. However I have some good news. I also wrote a work-around for the table view not deselecting issue. Could you try it out? (1.3.0) and confirm the issue has been resolved?

**Comment by FUNKYJASPER2** [comment]
> Hi Jasper,
> 
> You are right. It is confusing since the two issues weren't related. It should have been separated in different issues. However I have some good news. I also wrote a work-around for the table view not deselecting issue. Could you try it out? (1.3.0) and confirm the issue has been resolved?

No worries, and the issue has been fixed. Thanks a lot for the quick updates!!
